spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/identity-dev-db
        username: root
        password: password1234
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
