spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/identity-management-dev-db
        username: root
        password: password1234
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
