name: Build Check

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'kubernetes/**'
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'kubernetes/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: |
          cd microservices
          mvn clean install

      - name: Run unit tests
        run: |
          cd microservices
          mvn test

      - name: Check test results
        run: |
          cd microservices
          mvn surefire-report:report-only
          cat target/site/surefire-report.html

      - name: Publish to GitHub Packages
        run: |
          cd microservices
          echo "registry=https://maven.pkg.github.com/mcblankenburg/skytrader24" >> .mvn/wagon/github/overrides.xml
          echo "username=${{ github.actor }}" >> .mvn/wagon/github/overrides.xml
          echo "password=${{ secrets.GH_TOKEN }}" >> .mvn/wagon/github/overrides.xml
          ./mvnw deploy -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.http.retryHandler.retry=true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}