name: Build Check

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'kubernetes/**'
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'kubernetes/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: |
          cd microservices
          mvn clean install

      - name: Run unit tests
        run: |
          cd microservices
          mvn test

      - name: Check test results
        run: |
          cd microservices
          mvn surefire-report:report-only
          cat target/site/surefire-report.html

      - name: Publish to GitHub Packages
        run: |
          cd microservices
          echo "//maven.pkg.github.com/mcblankenburg/skytrader24/:registryToken=$GITHUB_TOKEN" > .npmrc
          mvn deploy -Dmaven.deploy.skip=true -Dmaven.repo.local=$HOME/.m2/repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}